// ─── CLOUDINARY HELPER ──────────────────────────────────────────────────────
// Builds a Cloudinary delivery URL for a given public_id.
// opts: any Cloudinary transformation string (defaults to 700px wide, auto quality)
const CDN = 'https://res.cloudinary.com/dqwlyubse/image/upload';

function cloudUrl(publicId, opts = 'w_700,q_auto,f_auto') {
  return `${CDN}/${opts}/${publicId}`;
}

// ─── ALBUM REGISTRY ──────────────────────────────────────────────────────────
// Each album entry:
//   id       — unique slug
//   title    — display name
//   tag      — category label shown on the card
//   cover    — public_id of the cover photo (first image shown on work/category pages)
//   photos   — array of public_ids for the full gallery (event.html)
//   folder   — Cloudinary folder path (used if Netlify function is available)
//
// To add a new album: upload photos to Cloudinary, note the public_ids,
// add an entry here, and the site updates automatically.

const LOCAL_ALBUMS = [
  {
    id:     'koe-wetzel',
    title:  'Koe Wetzel',
    tag:    'ChiliFest 2025',
    folder: 'Events/College-Station/Chili-Fest/Koe-Wetzel',
    cover:  'Koe-Wetzel-2_gz37h1',
    photos: [
      'Koe-Wetzel-1_wll1st',
      'Koe-Wetzel-2_gz37h1',
      'Koe-Wetzel-3_bjkjmf',
      'Koe-Wetzel-4_uxeuaa',
      'Koe-Wetzel-5_bfgjoi',
      'Koe-Wetzel-6_ym6aww',
      'Koe-Wetzel-7_e5wfor',
      'Koe-Wetzel-8_lopq7l',
      'Koe-Wetzel-9_ofq23x',
      'Koe-Wetzel-10_p13yti',
      'Koe-Wetzel-11_n4gufw',
      'Koe-Wetzel-12_xv7ts9',
      'Koe-Wetzel-13_ac1qdz',
      'Koe-Wetzel-14_o3d9dh',
      'Koe-Wetzel-15_obi0m4',
      'Koe-Wetzel-16_ue0el1',
      'Koe-Wetzel-17_j46p1o',
    ]
  },
  {
    id:     'josh-abbott',
    title:  'Josh Abbott',
    tag:    'ChiliFest 2025',
    folder: 'Events/College-Station/Chili-Fest/Josh-Abbott',
    cover:  'People-of-Chili-33_ko5lsh',
    photos: [
      'Josh-Abbot-1_a9mylx',
      'Josh-Abbot-2_fi8mft',
      'Josh-Abbot-3_nlebqu',
      'Josh-Abbot-4_aksjzo',
      'Josh-Abbot-5_g2lxf9',
      'Josh-Abbot-6_fcxosv',
      'Josh-Abbot-7_rginva',
      'Josh-Abbot-8_duk8cu',
      'People-of-Chili-33_ko5lsh',
    ]
  },
  {
    id:     'treaty-oak',
    title:  'Treaty Oak Revival',
    tag:    'ChiliFest 2025',
    folder: 'Events/College-Station/Chili-Fest/Treaty-Oak-Revival',
    cover:  'Treaty-Oak-8_pj5l0c',
    photos: [
      'Treaty-Oak-1_sdqjgq',
      'Treaty-Oak-2_udvhbm',
      'Treaty-Oak-3_p4jntb',
      'Treaty-Oak-4_gjos2h',
      'Treaty-Oak-5_cwrnff',
      'Treaty-Oak-6_lqtvgd',
      'Treaty-Oak-7_bxrpi6',
      'Treaty-Oak-7-2_ms1l6o',
      'Treaty-Oak-8_pj5l0c',
      'Treaty-Oak-9_z1yj0z',
      'Treaty-Oak-10_kuoyzz',
      'Treaty-Oak-11_tllrlr',
      'Treaty-Oak-12_rughk4',
      'Treaty-Oak-13_rek4q9',
    ]
  },
  {
    id:     'people-of-chili',
    title:  'People of Chili',
    tag:    'ChiliFest 2025',
    folder: 'Events/College-Station/Chili-Fest/PEOPLE-OF-CHILI',
    cover:  'People-of-Chili-51_rdlkw9',
    photos: [
      'People-of-Chili-1_vet7zz',
      'People-of-Chili-2_qo0rbv',
      'People-of-Chili-3_ts1gda',
      'People-of-Chili-4_pdbdan',
      'People-of-Chili-5_chck2w',
      'People-of-Chili-6_bdkcsu',
      'People-of-Chili-7_zscdho',
      'People-of-Chili-8_pu24cb',
      'People-of-Chili-9_ayzfsr',
      'People-of-Chili-10_yqt9t1',
      'People-of-Chili-12_szvz8e',
      'People-of-Chili-13_ljjwfq',
      'People-of-Chili-14_ytfhxf',
      'People-of-Chili-15_zfpiir',
      'People-of-Chili-16_eayz7b',
      'People-of-Chili-17_txezdj',
      'People-of-Chili-18_hcye72',
      'People-of-Chili-19_wxqk4e',
      'People-of-Chili-20_cihhk5',
      'People-of-Chili-21_jkdepm',
      'People-of-Chili-22_m8wl1a',
      'People-of-Chili-23_wioem4',
      'People-of-Chili-24_dqg6im',
      'People-of-Chili-25_wmtd9f',
      'People-of-Chili-26_kb2yz0',
      'People-of-Chili-27_jfednx',
      'People-of-Chili-28_uwarcm',
      'People-of-Chili-29_os8thi',
      'People-of-Chili-30_rg5r7b',
      'People-of-Chili-31_nyaris',
      'People-of-Chili-32_gjv5nt',
      'People-of-Chili-33_ko5lsh',
      'People-of-Chili-34_qk72mo',
      'People-of-Chili-35_vtqhed',
      'People-of-Chili-36_yg1kxq',
      'People-of-Chili-37_qe4vqy',
      'People-of-Chili-38_bhhkjg',
      'People-of-Chili-39_ryyxux',
      'People-of-Chili-40_szy4fc',
      'People-of-Chili-41_grpyiy',
      'People-of-Chili-42_yeyfdf',
      'People-of-Chili-43_pqbwfh',
      'People-of-Chili-44_pqmaub',
      'People-of-Chili-45_r6c0au',
      'People-of-Chili-46_gx7rr0',
      'People-of-Chili-47_fqhrbg',
      'People-of-Chili-48_dow12l',
      'People-of-Chili-48-2_q4ep1f',
      'People-of-Chili-49_vdpduu',
      'People-of-Chili-50_cu7xgx',
      'People-of-Chili-51_rdlkw9',
      'People-of-Chili-52_tliqgv',
      'People-of-Chili-53_fn4u7e',
      'People-of-Chili-54_us7jza',
      'People-of-Chili-55_mjfjlq',
      'People-of-Chili-56_if1bsl',
      'People-of-Chili-57_qwtq3t',
    ]
  },
  {
    id:     'douglass-showcase',
    title:  'Douglass Showcase',
    tag:    'EOP Basketball',
    folder: 'Events/Sports/EOP-Basketball/Douglass Showcase',
    cover:  'Douglass-Showcase-Selects-51_qlzhpp',
    photos: [
      'Douglass-Showcase-Selects-1_qw0iyr',
      'Douglass-Showcase-Selects-2_z3zi5t',
      'Douglass-Showcase-Selects-3_jiazat',
      'Douglass-Showcase-Selects-4_xj1iru',
      'Douglass-Showcase-Selects-5_fuzrfp',
      'Douglass-Showcase-Selects-6_ocwwvc',
      'Douglass-Showcase-Selects-7_mffpe3',
      'Douglass-Showcase-Selects-8_s8kpgy',
      'Douglass-Showcase-Selects-9_ry20gn',
      'Douglass-Showcase-Selects-10_d0l0uz',
      'Douglass-Showcase-Selects-11_cj1jw6',
      'Douglass-Showcase-Selects-12_e17xt3',
      'Douglass-Showcase-Selects-13_osxlia',
      'Douglass-Showcase-Selects-14_idcrbd',
      'Douglass-Showcase-Selects-15_jcetmb',
      'Douglass-Showcase-Selects-16_fvixb3',
      'Douglass-Showcase-Selects-17_kwpz2j',
      'Douglass-Showcase-Selects-18_ym10gk',
      'Douglass-Showcase-Selects-19_dh1jub',
      'Douglass-Showcase-Selects-20_n6bzhs',
      'Douglass-Showcase-Selects-21_dsvi8u',
      'Douglass-Showcase-Selects-22_lwqy0i',
      'Douglass-Showcase-Selects-23_uk2gui',
      'Douglass-Showcase-Selects-24_s0otbj',
      'Douglass-Showcase-Selects-25_s1vk2r',
      'Douglass-Showcase-Selects-26_vicbnt',
      'Douglass-Showcase-Selects-27_sqpixj',
      'Douglass-Showcase-Selects-28_otqjm7',
      'Douglass-Showcase-Selects-29_zm3sfi',
      'Douglass-Showcase-Selects-30_zxkn9r',
      'Douglass-Showcase-Selects-31_rwbegy',
      'Douglass-Showcase-Selects-32_kf2tf5',
      'Douglass-Showcase-Selects-33_ovi9yf',
      'Douglass-Showcase-Selects-34_tguc51',
      'Douglass-Showcase-Selects-35_l6kknd',
      'Douglass-Showcase-Selects-36_bx3w7w',
      'Douglass-Showcase-Selects-37_iwwos9',
      'Douglass-Showcase-Selects-38_x15d9z',
      'Douglass-Showcase-Selects-39_qkiq4h',
      'Douglass-Showcase-Selects-40_atx0nd',
      'Douglass-Showcase-Selects-41_v4ajnb',
      'Douglass-Showcase-Selects-42_x2fq15',
      'Douglass-Showcase-Selects-43_anmzro',
      'Douglass-Showcase-Selects-44_laarvd',
      'Douglass-Showcase-Selects-45_mk4urj',
      'Douglass-Showcase-Selects-46_mwmgli',
      'Douglass-Showcase-Selects-47_xrwvq8',
      'Douglass-Showcase-Selects-48_v2kp49',
      'Douglass-Showcase-Selects-49_qz10fm',
      'Douglass-Showcase-Selects-50_bhstvw',
      'Douglass-Showcase-Selects-51_qlzhpp',
      'Douglass-Showcase-Selects-52_nq4kuv',
      'Douglass-Showcase-Selects-53_mt4bft',
      'Douglass-Showcase-Selects-54_wboriw',
      'Douglass-Showcase-Selects-55_hysmwg',
      'Douglass-Showcase-Selects-56_imhgno',
      'Douglass-Showcase-Selects-57_vdbvdy',
      'Douglass-Showcase-Selects-58_sgz7qn',
      'Douglass-Showcase-Selects-59_kifyy7',
      'Douglass-Showcase-Selects-60_xeehxi',
      'Douglass-Showcase-Selects-61_cem6yg',
      'Douglass-Showcase-Selects-62_gkb0vj',
      'Douglass-Showcase-Selects-63_nzxvy2',
      'Douglass-Showcase-Selects-64_gswuf3',
      'Douglass-Showcase-Selects-65_x5ttq2',
      'Douglass-Showcase-Selects-66_ulnkdt',
      'Douglass-Showcase-Selects-67_pfpzom',
      'Douglass-Showcase-Selects-68_hvlf1a',
      'Douglass-Showcase-Selects-69_ztw0oe',
      'Douglass-Showcase-Selects-70_eqluiz',
      'Douglass-Showcase-Selects-71_zomnj1',
      'Douglass-Showcase-Selects-72_dgsvtj',
      'Douglass-Showcase-Selects-73_ll2q9j',
      'Douglass-Showcase-Selects-74_uwhe4q',
      'Douglass-Showcase-Selects-75_unuhct',
      'Douglass-Showcase-Selects-76_rsh862',
      'Douglass-Showcase-Selects-77_hk3wjn',
      'Douglass-Showcase-Selects-78_otojzc',
      'Douglass-Showcase-Selects-79_vyjjy3',
      'Douglass-Showcase-Selects-80_hqikkw',
      'Douglass-Showcase-Selects-81_gfw5sv',
      'Douglass-Showcase-Selects-82_bvrmpq',
      'Douglass-Showcase-Selects-83_xtkqlx',
      'Douglass-Showcase-Selects-84_vcd6df',
      'Douglass-Showcase-Selects-85_egnjaw',
      'Douglass-Showcase-Selects-86_kzs4qk',
      'Douglass-Showcase-Selects-87_vqp5jr',
      'Douglass-Showcase-Selects-88_tkhrlw',
      'Douglass-Showcase-Selects-89_wwjqxj',
      'Douglass-Showcase-Selects-90_reofzs',
      'Douglass-Showcase-Selects-91_pqimrl',
      'Douglass-Showcase-Selects-92_xtvn5o',
      'Douglass-Showcase-Selects-93_lxks47',
      'Douglass-Showcase-Selects-94_ghfora',
      'Douglass-Showcase-Selects-95_hchuxs',
      'Douglass-Showcase-Selects-96_xzzh9x',
      'Douglass-Showcase-Selects-97_k9kpha',
      'Douglass-Showcase-Selects-98_ds0goa',
      'Douglass-Showcase-Selects-99_cl92ef',
      'Douglass-Showcase-Selects-100_rvkoyz',
      'Douglass-Showcase-Selects-101_s8zzn3',
      'Douglass-Showcase-Selects-102_db34gc',
      'Douglass-Showcase-Selects-103_pcqtvn',
      'Douglass-Showcase-Selects-104_qmr3hk',
      'Douglass-Showcase-Selects-105_apueab',
    ]
  },
  {
    id:     'swaic-kickoff',
    title:  'SWAIC Kickoff',
    tag:    'EOP Basketball',
    folder: 'Events/Sports/EOP-Basketball/SWAIC-Kickoff',
    cover:  'SWAIC-Selects-42_gkkvyn',
    photos: [
      'SWAIC-Selects-1_xiqrlq',
      'SWAIC-Selects-2_hp2uss',
      'SWAIC-Selects-3_aiwrry',
      'SWAIC-Selects-4_yg0ytm',
      'SWAIC-Selects-5_fx6vud',
      'SWAIC-Selects-6_usylgm',
      'SWAIC-Selects-7_g7m6uj',
      'SWAIC-Selects-8_gorugj',
      'SWAIC-Selects-9_reljry',
      'SWAIC-Selects-10_pxnne6',
      'SWAIC-Selects-11_v4gpfg',
      'SWAIC-Selects-12_mm5h2b',
      'SWAIC-Selects-13_sivm2n',
      'SWAIC-Selects-14_cmla3v',
      'SWAIC-Selects-15_i5roct',
      'SWAIC-Selects-16_ui3dah',
      'SWAIC-Selects-17_r2cetc',
      'SWAIC-Selects-18_jbivim',
      'SWAIC-Selects-19_rtcvme',
      'SWAIC-Selects-20_pnz2sz',
      'SWAIC-Selects-21_mgeudm',
      'SWAIC-Selects-22_jtfuqb',
      'SWAIC-Selects-23_nfyqby',
      'SWAIC-Selects-24_nlaeb7',
      'SWAIC-Selects-25_b2fubc',
      'SWAIC-Selects-26_fucbmh',
      'SWAIC-Selects-27_qyhvcv',
      'SWAIC-Selects-28_q4fr4z',
      'SWAIC-Selects-29_knvgls',
      'SWAIC-Selects-30_cqevon',
      'SWAIC-Selects-31_hsozde',
      'SWAIC-Selects-32_igyjq7',
      'SWAIC-Selects-33_cbryef',
      'SWAIC-Selects-34_oun5cd',
      'SWAIC-Selects-35_rq0vpx',
      'SWAIC-Selects-36_kgltxs',
      'SWAIC-Selects-37_zcpl9y',
      'SWAIC-Selects-38_azkpxp',
      'SWAIC-Selects-39_jbyacv',
      'SWAIC-Selects-40_prf15y',
      'SWAIC-Selects-41_mjlytn',
      'SWAIC-Selects-42_gkkvyn',
      'SWAIC-Selects-43_vwzbhe',
      'SWAIC-Selects-44_rtn8ka',
      'SWAIC-Selects-45_zm2d1e',
      'SWAIC-Selects-46_zoapco',
      'SWAIC-Selects-47_x05y0b',
      'SWAIC-Selects-48_qhufcd',
      'SWAIC-Selects-49_ggsork',
      'SWAIC-Selects-50_bcfowb',
      'SWAIC-Selects-51_axldnl',
      'SWAIC-Selects-52_mbgasb',
      'SWAIC-Selects-53_ny1etz',
      'SWAIC-Selects-54_i1gv57',
      'SWAIC-Selects-55_xhdvfm',
      'SWAIC-Selects-56_je9d2p',
      'SWAIC-Selects-57_ntezyn',
      'SWAIC-Selects-58_t55kid',
      'SWAIC-Selects-59_y5f8id',
      'SWAIC-Selects-60_yld3l6',
      'SWAIC-Selects-61_nqitxs',
      'SWAIC-Selects-62_nmshje',
      'SWAIC-Selects-63_kjeae4',
      'SWAIC-Selects-64_zwg4cx',
      'SWAIC-Selects-65_rgvbnl',
      'SWAIC-Selects-66_q9wldo',
      'SWAIC-Selects-67_kjznue',
      'SWAIC-Selects-68_wcavxi',
      'SWAIC-Selects-69_excobu',
      'SWAIC-Selects-70_ddo3mn',
      'SWAIC-Selects-71_alccad',
      'SWAIC-Selects-72_drtlln',
      'SWAIC-Selects-73_ffz1al',
      'SWAIC-Selects-74_cnyzsy',
      'SWAIC-Selects-75_hw0xat',
      'SWAIC-Selects-76_fydeg3',
      'SWAIC-Selects-77_sjkw57',
      'SWAIC-Selects-78_qnfhix',
      'SWAIC-Selects-79_byysql',
      'SWAIC-Selects-80_pz41im',
      'SWAIC-Selects-81_enzkql',
      'SWAIC-Selects-82_kc1abg',
      'SWAIC-Selects-83_lctfgk',
      'SWAIC-Selects-84_c5o9ts',
      'SWAIC-Selects-85_oclnh8',
    ]
  },
  {
    id:     'parker-grad',
    title:  'Parker — Grad Photos',
    tag:    'Grad Photos',
    folder: 'Events/College-Station/Grad-Photos/Parker-Grad',
    cover:  'Parker-Grad-Photos-1_hklcfa',
    photos: [
      'Parker-Grad-Photos-1_hklcfa',
      'Parker-Grad-Photos-2_gy38l4',
      'Parker-Grad-Photos-3_gomspk',
      'Parker-Grad-Photos-4_asmxwf',
      'Parker-Grad-Photos-5_ujknps',
      'Parker-Grad-Photos-6_kldvl9',
      'Parker-Grad-Photos-7_lqc6x1',
      'Parker-Grad-Photos-8_lv9as6',
      'Parker-Grad-Photos-9_xcooie',
      'Parker-Grad-Photos-10_rt2uke',
      'Parker-Grad-Photos-11_ovekmw',
      'Parker-Grad-Photos-12_nut8nv',
      'Parker-Grad-Photos-13_rmcz5e',
      'Parker-Grad-Photos-14_mbz4wt',
      'Parker-Grad-Photos-15_ggkqie',
      'Parker-Grad-Photos-16_oxvbd1',
      'Parker-Grad-Photos-17_pui4im',
      'Parker-Grad-Photos-18_u3b1tr',
      'Parker-Grad-Photos-19_in9gou',
      'Parker-Grad-Photos-20_hvle5d',
    ]
  },
  {
    id:     'jennas-ring-dunk',
    title:  "Jenna's Ring Dunk",
    tag:    'Grad Photos',
    folder: 'Events/College-Station/Grad-Photos/Jennas-Ring-Dunk',
    cover:  'Jennas-Ring-Dunk-30_uvnvvv',
    photos: [
      'Jennas-Ring-Dunk-1_eenjyk',
      'Jennas-Ring-Dunk-2_cy4q40',
      'Jennas-Ring-Dunk-3_eqdxzs',
      'Jennas-Ring-Dunk-4_trywfu',
      'Jennas-Ring-Dunk-5_rnnp45',
      'Jennas-Ring-Dunk-6_hicrre',
      'Jennas-Ring-Dunk-7_tawhoe',
      'Jennas-Ring-Dunk-8_up0wes',
      'Jennas-Ring-Dunk-9_tztmon',
      'Jennas-Ring-Dunk-10_yave2j',
      'Jennas-Ring-Dunk-11_pavbsv',
      'Jennas-Ring-Dunk-12_m1rz4e',
      'Jennas-Ring-Dunk-13_fyhrph',
      'Jennas-Ring-Dunk-14_lh2cl3',
      'Jennas-Ring-Dunk-15_uiuzd2',
      'Jennas-Ring-Dunk-16_zokh6c',
      'Jennas-Ring-Dunk-17_jhixos',
      'Jennas-Ring-Dunk-18_wj8vgu',
      'Jennas-Ring-Dunk-19_q0vu6r',
      'Jennas-Ring-Dunk-20_b6g94i',
      'Jennas-Ring-Dunk-21_m0opcy',
      'Jennas-Ring-Dunk-22_cfcbtp',
      'Jennas-Ring-Dunk-23_lvmu67',
      'Jennas-Ring-Dunk-24_itsnec',
      'Jennas-Ring-Dunk-25_kaoiov',
      'Jennas-Ring-Dunk-26_ybcjfl',
      'Jennas-Ring-Dunk-27_z333cx',
      'Jennas-Ring-Dunk-28_dco4wa',
      'Jennas-Ring-Dunk-29_voqguf',
      'Jennas-Ring-Dunk-30_uvnvvv',
      'Jennas-Ring-Dunk-31_xz9pkc',
      'Jennas-Ring-Dunk-32_zhlq8t',
      'Jennas-Ring-Dunk-33_kedwlx',
      'Jennas-Ring-Dunk-34_itp4mg',
      'Jennas-Ring-Dunk-35_lc3mwt',
    ]
  },
  {
    id:     'group-grad-photos',
    title:  'Group Grad Photos',
    tag:    'Grad Photos',
    folder: 'Events/College-Station/Grad-Photos/Group-Grad-Photos',
    cover:  'Group-Grad-Photos-5_nxzfiv',
    photos: [
      'Group-Grad-Photos-1_hm8sy5',
      'Group-Grad-Photos-2_kqt8at',
      'Group-Grad-Photos-3_vv31c5',
      'Group-Grad-Photos-4_kuwvow',
      'Group-Grad-Photos-5_nxzfiv',
      'Group-Grad-Photos-6_ujid1g',
      'Group-Grad-Photos-7_aho9kh',
      'Group-Grad-Photos-8_ihzv7a',
      'Group-Grad-Photos-9_ewx3ex',
      'Group-Grad-Photos-10_x2tlru',
      'Group-Grad-Photos-11_fwjvxl',
      'Group-Grad-Photos-12_nyv2pc',
      'Group-Grad-Photos-13_fau04w',
      'Group-Grad-Photos-14_ey71xj',
      'Group-Grad-Photos-15_f2gqun',
      'Group-Grad-Photos-16_irhwqe',
      'Group-Grad-Photos-17_sa1hkn',
      'Group-Grad-Photos-18_ijak5u',
      'Group-Grad-Photos-19_drxohd',
      'Group-Grad-Photos-20_ukyrae',
      'Group-Grad-Photos-21_uunswt',
      'Group-Grad-Photos-22_md1zlb',
      'Group-Grad-Photos-23_i5mphj',
      'Group-Grad-Photos-24_uhnqgq',
      'Group-Grad-Photos-25_cc2z4m',
      'Group-Grad-Photos-26_s4bpon',
      'Group-Grad-Photos-27_rkg9ou',
      'Group-Grad-Photos-28_qny5rp',
      'Group-Grad-Photos-29_b5s8no',
    ]
  },
  {
    id:     'karly-corey',
    title:  'Karly & Corey',
    tag:    'Weddings',
    folder: 'Events/Weddings/Karly-Corey',
    cover:  'ChatGPT_Image_Apr_29_2026_07_05_53_PM_v8z8k9',
    photos: [
      'Core-Karly-1_kauya1',
      'Corey-Karly-2_n2grb6',
      'Corey-Karly-3_xwogxi',
      'Corey-Karly-4_mkxkxt',
      'Corey-Karly-5_drht96',
      'Corey-Karly-6_ukwlwc',
      'Corey-Karly-7_zmmrxt',
      'Corey-Karly-8_ck7bq0',
      'Corey-Karly-9_q2n9sf',
      'Corey-Karly-10_cyop9w',
      'Corey-Karly-12_sm5yrg',
      'Core-Karly-13_fyknra',
      'Corey-Karly-13_ik0hbi',
      'Corey-Karly-14_jau5vd',
      'Corey-Karly-15_kzbax4',
      'ChatGPT_Image_Apr_29_2026_07_05_53_PM_v8z8k9',
      'Corey-Karly-17_twukei',
    ]
  },
  {
    id:     'madison-sam',
    title:  'Madison & Sam',
    tag:    'Weddings',
    folder: 'Events/Weddings/Madison-Sam',
    cover:  'joshs-weddings-09_gufvoh',
    photos: [
      'joshs-weddings-01_ex8yeq',
      'joshs-weddings-02_qolsgm',
      'joshs-weddings-07_yzw4r9',
      'joshs-weddings-08_hhbio6',
      'joshs-weddings-09_gufvoh',
      'joshs-weddings-10_nco7oh',
      'joshs-weddings-11_wtl4xu',
      'joshs-weddings-12_xujhpd',
    ]
  },
  {
    id:     'ralynn-paul',
    title:  'Ralynn & Paul',
    tag:    'Weddings',
    folder: 'Events/Weddings/Ralynn-Paul',
    cover:  'joshs-weddings-14_husq8v',
    photos: [
      'joshs-weddings-04_wf2dlo',
      'joshs-weddings-05_oss9yw',
      'joshs-weddings-06_vqrwyo',
      'joshs-weddings-14_husq8v',
      'joshs-weddings-15_vacstn',
      'joshs-weddings-16_yfktcf',
      'joshs-weddings-17_idjc4z',
      'joshs-weddings-18_gnpqnq',
    ]
  },
  {
    id:     'nathan-grad',
    title:  'Nathan Gil — Class of 2024',
    tag:    'Grad Photos',
    folder: 'Events/College-Station/Grad-Photos/Nathan-Gil',
    cover:  'Nathan-Grad-32_l9slbg',
    photos: [
      'Nathan-Grad-32_l9slbg',
      'Nathan-Grad-1_uxx7ys',
      'Nathan-Grad-2_fay4w3',
      'Nathan-Grad-3_sv86xx',
      'Nathan-Grad-4_ntvfkb',
      'Nathan-Grad-5_oqctq2',
      'Nathan-Grad-6_zbwr73',
      'Nathan-Grad-7_ikwvyb',
      'Nathan-Grad-8_mwdpyl',
      'Nathan-Grad-9_oj68ky',
      'Nathan-Grad-10_am5d6k',
      'Nathan-Grad-11_gmpilz',
      'Nathan-Grad-13_ttniyw',
      'Nathan-Grad-14_si1qbc',
      'Nathan-Grad-15_vyr6x6',
      'Nathan-Grad-16_yirpkf',
      'Nathan-Grad-17_x9hdyj',
      'Nathan-Grad-18_cx1wnn',
      'Nathan-Grad-19_kvzncy',
      'Nathan-Grad-20_t21hvo',
      'Nathan-Grad-21_tcodm0',
      'Nathan-Grad-22_j2xobi',
      'Nathan-Grad-23_maugsn',
      'Nathan-Grad-24_wqyiql',
      'Nathan-Grad-25_wme0ni',
      'Nathan-Grad-26_nnv6ua',
      'Nathan-Grad-27_bz0pur',
      'Nathan-Grad-28_xlhelr',
      'Nathan-Grad-29_y0k3hg',
      'Nathan-Grad-30_grmgjd',
      'Nathan-Grad-31_touldj',
      'Nathan-Grad-33_quzshp',
      'Nathan-Grad-34_ymxyoh',
      'Nathan-Grad-35_dufa5s',
      'Nathan-Grad-36_ogiixt',
      'Nathan-Grad-37_vvsj68',
      'Nathan-Grad-38_ngo34a',
      'Nathan-Grad-39_vvrn2j',
      'Nathan-Grad-40_wcgnpt',
      'Nathan-Grad-41_fxkfjp',
      'Nathan-Grad-42_rie0jk',
      'Nathan-Grad-43_d7wfsg',
      'Nathan-Grad-44_ywec3n',
      'Nathan-Grad-45_jaedmm',
      'Nathan-Grad-46_wyjgsw',
      'Nathan-Grad-47_wdpciw',
      'Nathan-Grad-49_a4z4wf',
      'Nathan-Grad-50_suv8g9',
      'Nathan-Grad-51_pcrsne',
    ]
  },
];

// ─── CATEGORY REGISTRY ────────────────────────────────────────────────────────
// Groups albums into display categories shown on the Work page.
// albumIds references LOCAL_ALBUMS ids above.
// cover: public_id for the category card thumbnail.
const LOCAL_CATEGORIES = [
  {
    id:       'chilifest',
    title:    'ChiliFest 2025',
    tag:      'ChiliFest 2025',
    cover:    'Koe-Wetzel-1_wll1st',
    albumIds: ['koe-wetzel', 'josh-abbott', 'treaty-oak', 'people-of-chili'],
  },
  {
    id:       'basketball',
    title:    'EOP Basketball',
    tag:      'EOP Basketball',
    cover:    'Douglass-Showcase-Selects-1_qw0iyr',
    albumIds: ['douglass-showcase', 'swaic-kickoff'],
  },
  {
    id:       'grad-photos',
    title:    'Grad Photos',
    tag:      'Grad Photos',
    cover:    'Nathan-Grad-32_l9slbg',
    albumIds: ['nathan-grad', 'parker-grad', 'jennas-ring-dunk', 'group-grad-photos'],
  },
  {
    id:       'weddings',
    title:    'Weddings',
    tag:      'Weddings',
    cover:    'ChatGPT_Image_Apr_29_2026_07_05_53_PM_v8z8k9',
    albumIds: ['karly-corey', 'madison-sam', 'ralynn-paul'],
  },
];
